### ISSUE TITLE
Loads but remains on 'Finishing up' message

### ISSUE THREAD

**Issue by jaspotn** [johanw666/StarTrekTimelinesSpreadsheet#7]
**Describe the bug**
I launch the application and it runs through the various messages of collecting data and when it reaches the 'Finishing up' stage, it fails to finish and show the application.

**To Reproduce**
1. Launch the application
2. Wait for it to load the assets
3. Observe the 'Finishing up' message

**Expected behavior**
The application would load the main interface

**Screenshots**
![image](https://user-images.githubusercontent.com/39434813/73446386-91562800-43ac-11ea-8785-dcf85cd4ec33.png)

**Additional context**
I have removed and reinstalled the application, ensured the bundle.js file has api v12 and client version 7.4.0. I also removed the 'C:\Users\user\AppData\Roaming\Star Trek Timelines Crew Management' folder as mentioned with other issues and ran as admin but same issue occurs.

**Comment by johanw666** [comment]
I noted that after I renamed the data directory AppData\Roaming\Star Trek Timelines Crew Management, and started the program with admin rights it works. After that I copied over the imagecache to the newly created datadir. I now run it as admin and that still works for me.

If you already removed the imagecache you will find it will not download the images again, you can find my copy on https://mega.nz/#!BUhUVAgI!7r3x2uHUuSIWMaD2MS-kyFyoxl3FSxO_eF30gAuivzE

**Comment by s3828158** [comment]
Thanks for that, after I downloaded your folder and put the images back it now loads. I had tried a few times to get it going so with all the changing my images were gone so now I have them back it seems to work. So it seems it can't download that again.

I wonder if this means that new images will also no download, leading to the app breaking entirely? I've got the Win10 app installed and I can see that there are folders there with the names so that stores them in a different format meaning they can't be duplicated across.

Oh well, thanks for that and keeping the app alive, at least for now it's working and this bug can be closed.
